import { Category, Collection, ProductWithDetails } from './types';

export const SEED_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'T-Shirts & Tops', slug: 't-shirts', display_order: 1 },
  { id: 'cat-2', name: 'Shirts', slug: 'shirts', display_order: 2 },
  { id: 'cat-3', name: 'Hoodies & Sweats', slug: 'hoodies', display_order: 3 },
  { id: 'cat-4', name: 'Jackets & Outerwear', slug: 'jackets', display_order: 4 },
  { id: 'cat-5', name: 'Bottoms', slug: 'bottoms', display_order: 5 },
];

export const SEED_COLLECTIONS: Collection[] = [
  {
    id: 'col-1',
    name: 'New Arrivals',
    slug: 'new-arrivals',
    description: 'The latest drop of architectural streetwear & minimal editorial artifacts.',
    is_curated: true,
    display_order: 1,
  },
  {
    id: 'col-2',
    name: 'Best Sellers',
    slug: 'best-sellers',
    description: 'Our most demanded monolithic silhouettes and perennial wardrobe foundations.',
    is_curated: true,
    display_order: 2,
  },
  {
    id: 'col-3',
    name: 'Heavy Hoodies',
    slug: 'heavy-hoodies',
    description: 'Heavyweight 450 GSM French Terry cotton hoodies engineered for cold climates.',
    is_curated: true,
    display_order: 3,
  },
  {
    id: 'col-4',
    name: 'Technical Outerwear',
    slug: 'technical-outerwear',
    description: 'Water-repellent technical jackets with articulated seam architecture.',
    is_curated: true,
    display_order: 4,
  },
];

export const SEED_PRODUCTS: ProductWithDetails[] = [
  // =================== MALE (MENSWEAR) ===================
  {
    id: 'p-1',
    name: 'OVERSIZED COTTON TEE',
    slug: 'oversized-cotton-tee',
    description:
      'Engineered from 320 GSM combed organic cotton with twin-needle neck ribbing, dropped shoulders, and a geometric relaxed box cut.',
    category_id: 'cat-1',
    category: SEED_CATEGORIES[0],
    collections: [SEED_COLLECTIONS[0], SEED_COLLECTIONS[1]],
    mrp: 499900, // ₹4,999 INR
    sale_price: 499900,
    material: '100% Organic Combed Cotton (320 GSM)',
    fit: 'Relaxed Oversized Fit',
    care: 'Machine wash cold 30°C inside out. Do not tumble dry.',
    weight_g: 420,
    country_of_origin: 'India',
    gender: 'male',
    tags: ['male', 'cotton', 'oversized', 't-shirt', 'black', 'cream', 'men'],
    status: 'active',
    rating_average: 4.8,
    rating_count: 14,
    created_at: '2026-10-01T00:00:00Z',
    updated_at: '2026-10-01T00:00:00Z',
    images: [
      {
        id: 'img-1-1',
        product_id: 'p-1',
        colour: 'WASHED BLACK',
        url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
        alt_text: 'Front studio shot of Oversized Cotton Tee in Washed Black',
        position: 1,
        is_primary: true,
      },
      {
        id: 'img-1-2',
        product_id: 'p-1',
        colour: 'WASHED BLACK',
        url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
        alt_text: 'Back detail view of Oversized Cotton Tee shoulder seam',
        position: 2,
        is_primary: false,
      },
      {
        id: 'img-1-3',
        product_id: 'p-1',
        colour: 'RAW CREAM',
        url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80',
        alt_text: 'Front view of Oversized Cotton Tee in Raw Cream',
        position: 3,
        is_primary: false,
      },
    ],
    variants: [
      { id: 'v-1-s', product_id: 'p-1', sku: 'TEE-BLK-S', colour: 'WASHED BLACK', colour_hex: '#111111', size: 'S', stock: 8, reserved_stock: 0 },
      { id: 'v-1-m', product_id: 'p-1', sku: 'TEE-BLK-M', colour: 'WASHED BLACK', colour_hex: '#111111', size: 'M', stock: 12, reserved_stock: 0 },
      { id: 'v-1-l', product_id: 'p-1', sku: 'TEE-BLK-L', colour: 'WASHED BLACK', colour_hex: '#111111', size: 'L', stock: 5, reserved_stock: 0 },
      { id: 'v-1-xl', product_id: 'p-1', sku: 'TEE-BLK-XL', colour: 'WASHED BLACK', colour_hex: '#111111', size: 'XL', stock: 2, reserved_stock: 0 },
      { id: 'v-1-crm-m', product_id: 'p-1', sku: 'TEE-CRM-M', colour: 'RAW CREAM', colour_hex: '#F5F0E8', size: 'M', stock: 10, reserved_stock: 0 },
      { id: 'v-1-crm-l', product_id: 'p-1', sku: 'TEE-CRM-L', colour: 'RAW CREAM', colour_hex: '#F5F0E8', size: 'L', stock: 0, reserved_stock: 0 },
    ],
  },
  {
    id: 'p-2',
    name: 'HEAVYWEIGHT ZIP HOODIE',
    slug: 'heavyweight-zip-hoodie',
    description:
      'Constructed from 450 GSM double-faced French Terry with double-layered hood, heavy-gauge two-way matte black metal zip, and deep kangaroo pocket.',
    category_id: 'cat-3',
    category: SEED_CATEGORIES[2],
    collections: [SEED_COLLECTIONS[0], SEED_COLLECTIONS[2]],
    mrp: 899900, // ₹8,999 INR
    sale_price: 899900,
    material: '100% French Terry Cotton (450 GSM)',
    fit: 'Boxy Heavyweight Fit',
    care: 'Dry clean recommended or machine wash cold on delicate cycle.',
    weight_g: 980,
    country_of_origin: 'India',
    gender: 'male',
    tags: ['male', 'hoodie', 'zip', 'heavyweight', 'black', 'cream', 'men'],
    status: 'active',
    rating_average: 4.9,
    rating_count: 22,
    created_at: '2026-10-02T00:00:00Z',
    updated_at: '2026-10-02T00:00:00Z',
    images: [
      {
        id: 'img-2-1',
        product_id: 'p-2',
        colour: 'RAW CREAM',
        url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
        alt_text: 'Front view of Heavyweight Zip Hoodie in Raw Cream',
        position: 1,
        is_primary: true,
      },
      {
        id: 'img-2-2',
        product_id: 'p-2',
        colour: 'RAW CREAM',
        url: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=800&auto=format&fit=crop&q=80',
        alt_text: 'Hoodie double layer hood detail view',
        position: 2,
        is_primary: false,
      },
    ],
    variants: [
      { id: 'v-2-s', product_id: 'p-2', sku: 'HD-CRM-S', colour: 'RAW CREAM', colour_hex: '#F5F0E8', size: 'S', stock: 4, reserved_stock: 0 },
      { id: 'v-2-m', product_id: 'p-2', sku: 'HD-CRM-M', colour: 'RAW CREAM', colour_hex: '#F5F0E8', size: 'M', stock: 6, reserved_stock: 0 },
      { id: 'v-2-l', product_id: 'p-2', sku: 'HD-CRM-L', colour: 'RAW CREAM', colour_hex: '#F5F0E8', size: 'L', stock: 3, reserved_stock: 0 },
    ],
  },
  {
    id: 'p-3',
    name: 'STRUCTURED TAILORED SHIRT',
    slug: 'structured-tailored-shirt',
    description:
      'Woven from crisp 100% Poplin cotton with concealed horn button placket, sharp square collar, and clean single-button cuffs.',
    category_id: 'cat-2',
    category: SEED_CATEGORIES[1],
    collections: [SEED_COLLECTIONS[1]],
    mrp: 649900, // ₹6,499 INR
    sale_price: 649900,
    material: '100% Crisp Cotton Poplin',
    fit: 'Architectural Slim Fit',
    care: 'Warm iron, machine wash 40°C.',
    weight_g: 340,
    country_of_origin: 'India',
    gender: 'male',
    tags: ['male', 'shirt', 'poplin', 'black', 'formal', 'men'],
    status: 'active',
    rating_average: 4.7,
    rating_count: 8,
    created_at: '2026-10-03T00:00:00Z',
    updated_at: '2026-10-03T00:00:00Z',
    images: [
      {
        id: 'img-3-1',
        product_id: 'p-3',
        colour: 'DEEP BLACK',
        url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80',
        alt_text: 'Front view of Structured Tailored Shirt in Deep Black',
        position: 1,
        is_primary: true,
      },
    ],
    variants: [
      { id: 'v-3-s', product_id: 'p-3', sku: 'SH-BLK-S', colour: 'DEEP BLACK', colour_hex: '#111111', size: 'S', stock: 5, reserved_stock: 0 },
      { id: 'v-3-m', product_id: 'p-3', sku: 'SH-BLK-M', colour: 'DEEP BLACK', colour_hex: '#111111', size: 'M', stock: 9, reserved_stock: 0 },
      { id: 'v-3-l', product_id: 'p-3', sku: 'SH-BLK-L', colour: 'DEEP BLACK', colour_hex: '#111111', size: 'L', stock: 7, reserved_stock: 0 },
    ],
  },
  {
    id: 'p-4',
    name: 'TECHNICAL BOMBER JACKET',
    slug: 'technical-bomber-jacket',
    description:
      'Water-repellent nylon shell with satin interior lining, ribbed collar & cuffs, dual storm flap pockets, and sleeve utility compartment.',
    category_id: 'cat-4',
    category: SEED_CATEGORIES[3],
    collections: [SEED_COLLECTIONS[0], SEED_COLLECTIONS[3]],
    mrp: 1299900, // ₹12,999 INR
    sale_price: 1299900,
    material: '100% Water-Repellent Nylon Shell',
    fit: 'Structured Oversized Bomber',
    care: 'Specialist dry clean only.',
    weight_g: 850,
    country_of_origin: 'India',
    gender: 'male',
    tags: ['male', 'jacket', 'bomber', 'technical', 'black', 'men'],
    status: 'active',
    rating_average: 5.0,
    rating_count: 5,
    created_at: '2026-10-04T00:00:00Z',
    updated_at: '2026-10-04T00:00:00Z',
    images: [
      {
        id: 'img-4-1',
        product_id: 'p-4',
        colour: 'CHARCOAL BLACK',
        url: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?w=800&auto=format&fit=crop&q=80',
        alt_text: 'Technical Bomber Jacket studio front view',
        position: 1,
        is_primary: true,
      },
    ],
    variants: [
      { id: 'v-4-m', product_id: 'p-4', sku: 'JKT-BMB-M', colour: 'CHARCOAL BLACK', colour_hex: '#111111', size: 'M', stock: 3, reserved_stock: 0 },
      { id: 'v-4-l', product_id: 'p-4', sku: 'JKT-BMB-L', colour: 'CHARCOAL BLACK', colour_hex: '#111111', size: 'L', stock: 4, reserved_stock: 0 },
    ],
  },
  {
    id: 'p-5',
    name: 'RELAXED PLEATED TROUSERS',
    slug: 'relaxed-pleated-trousers',
    description:
      'Tailored wide-leg trousers featuring deep front pleats, adjustable waist tabs, welt rear pockets, and clean floor-length drape.',
    category_id: 'cat-5',
    category: SEED_CATEGORIES[4],
    collections: [SEED_COLLECTIONS[0]],
    mrp: 749900, // ₹7,499 INR
    sale_price: 749900,
    material: 'Wool-Blend Gabardine (65% Wool, 35% Poly)',
    fit: 'Wide Straight Leg',
    care: 'Dry clean only.',
    weight_g: 610,
    country_of_origin: 'India',
    gender: 'male',
    tags: ['male', 'trousers', 'pleated', 'bottoms', 'black', 'men'],
    status: 'active',
    rating_average: 4.6,
    rating_count: 11,
    created_at: '2026-10-05T00:00:00Z',
    updated_at: '2026-10-05T00:00:00Z',
    images: [
      {
        id: 'img-5-1',
        product_id: 'p-5',
        colour: 'CHARCOAL BLACK',
        url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80',
        alt_text: 'Relaxed Pleated Trousers full length front view',
        position: 1,
        is_primary: true,
      },
    ],
    variants: [
      { id: 'v-5-s', product_id: 'p-5', sku: 'TR-BLK-S', colour: 'CHARCOAL BLACK', colour_hex: '#111111', size: 'S', stock: 6, reserved_stock: 0 },
      { id: 'v-5-m', product_id: 'p-5', sku: 'TR-BLK-M', colour: 'CHARCOAL BLACK', colour_hex: '#111111', size: 'M', stock: 10, reserved_stock: 0 },
      { id: 'v-5-l', product_id: 'p-5', sku: 'TR-BLK-L', colour: 'CHARCOAL BLACK', colour_hex: '#111111', size: 'L', stock: 5, reserved_stock: 0 },
    ],
  },

  // =================== FEMALE (WOMENSWEAR) ===================
  {
    id: 'p-6',
    name: 'SCULPTURAL COCOON COAT',
    slug: 'sculptural-cocoon-coat',
    description:
      'Curved cocoon silhouette tailored from double-faced virgin wool melange. Features hidden snap button closure, dropped raglan sleeves, and deep angled side pockets.',
    category_id: 'cat-4',
    category: SEED_CATEGORIES[3],
    collections: [SEED_COLLECTIONS[0], SEED_COLLECTIONS[3]],
    mrp: 1499900, // ₹14,999 INR
    sale_price: 1499900,
    material: '100% Virgin Wool Melange (520 GSM)',
    fit: 'Architectural Cocoon Oversized Cut',
    care: 'Dry clean only by garment care specialists.',
    weight_g: 1100,
    country_of_origin: 'India',
    gender: 'female',
    tags: ['female', 'coat', 'wool', 'sculptural', 'outerwear', 'women'],
    status: 'active',
    rating_average: 4.9,
    rating_count: 18,
    created_at: '2026-10-06T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
    images: [
      {
        id: 'img-6-1',
        product_id: 'p-6',
        colour: 'RAW CHARCOAL',
        url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&auto=format&fit=crop&q=80',
        alt_text: 'Editorial portrait of Sculptural Cocoon Coat in Raw Charcoal',
        position: 1,
        is_primary: true,
      },
    ],
    variants: [
      { id: 'v-6-xs', product_id: 'p-6', sku: 'CCT-CHR-XS', colour: 'RAW CHARCOAL', colour_hex: '#333333', size: 'XS', stock: 4, reserved_stock: 0 },
      { id: 'v-6-s', product_id: 'p-6', sku: 'CCT-CHR-S', colour: 'RAW CHARCOAL', colour_hex: '#333333', size: 'S', stock: 7, reserved_stock: 0 },
      { id: 'v-6-m', product_id: 'p-6', sku: 'CCT-CHR-M', colour: 'RAW CHARCOAL', colour_hex: '#333333', size: 'M', stock: 5, reserved_stock: 0 },
    ],
  },
  {
    id: 'p-7',
    name: 'ASYMMETRIC DRAPED SILK BLOUSE',
    slug: 'asymmetric-draped-silk-blouse',
    description:
      'Fluid asymmetric high-neck blouse cut on the bias from heavyweight sandwashed mulberry silk crepe with elongated split cuffs and button fastening.',
    category_id: 'cat-2',
    category: SEED_CATEGORIES[1],
    collections: [SEED_COLLECTIONS[0]],
    mrp: 799900, // ₹7,999 INR
    sale_price: 799900,
    material: '100% Sandwashed Mulberry Silk Crepe',
    fit: 'Fluid Asymmetric Silhouette',
    care: 'Dry clean or gentle hand wash cold with silk detergent.',
    weight_g: 220,
    country_of_origin: 'India',
    gender: 'female',
    tags: ['female', 'blouse', 'silk', 'draped', 'cream', 'women'],
    status: 'active',
    rating_average: 4.8,
    rating_count: 9,
    created_at: '2026-10-06T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
    images: [
      {
        id: 'img-7-1',
        product_id: 'p-7',
        colour: 'OFF WHITE',
        url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80',
        alt_text: 'Asymmetric Draped Silk Blouse campaign look',
        position: 1,
        is_primary: true,
      },
    ],
    variants: [
      { id: 'v-7-xs', product_id: 'p-7', sku: 'SLK-WHT-XS', colour: 'OFF WHITE', colour_hex: '#FFFDF8', size: 'XS', stock: 6, reserved_stock: 0 },
      { id: 'v-7-s', product_id: 'p-7', sku: 'SLK-WHT-S', colour: 'OFF WHITE', colour_hex: '#FFFDF8', size: 'S', stock: 8, reserved_stock: 0 },
      { id: 'v-7-m', product_id: 'p-7', sku: 'SLK-WHT-M', colour: 'OFF WHITE', colour_hex: '#FFFDF8', size: 'M', stock: 4, reserved_stock: 0 },
    ],
  },
  {
    id: 'p-8',
    name: 'HIGH-RISE FLUID PALAZZO PANT',
    slug: 'high-rise-fluid-palazzo-pant',
    description:
      'High-waisted palazzo silhouette cut from Japanese matte triacetate twill. Features structured waist yoke, fluid movement, and concealed side zip.',
    category_id: 'cat-5',
    category: SEED_CATEGORIES[4],
    collections: [SEED_COLLECTIONS[1]],
    mrp: 849900, // ₹8,499 INR
    sale_price: 849900,
    material: 'Japanese Matte Triacetate Twill (100%)',
    fit: 'High-Rise Dramatic Wide Leg',
    care: 'Machine wash delicate cycle inside out.',
    weight_g: 480,
    country_of_origin: 'India',
    gender: 'female',
    tags: ['female', 'bottoms', 'trousers', 'palazzo', 'black', 'women'],
    status: 'active',
    rating_average: 4.7,
    rating_count: 12,
    created_at: '2026-10-06T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
    images: [
      {
        id: 'img-8-1',
        product_id: 'p-8',
        colour: 'OBSIDIAN BLACK',
        url: 'https://images.unsplash.com/photo-1551803091-e20673f15770?w=800&auto=format&fit=crop&q=80',
        alt_text: 'High-Rise Fluid Palazzo Pant styled in studio',
        position: 1,
        is_primary: true,
      },
    ],
    variants: [
      { id: 'v-8-s', product_id: 'p-8', sku: 'PLZ-BLK-S', colour: 'OBSIDIAN BLACK', colour_hex: '#111111', size: 'S', stock: 5, reserved_stock: 0 },
      { id: 'v-8-m', product_id: 'p-8', sku: 'PLZ-BLK-M', colour: 'OBSIDIAN BLACK', colour_hex: '#111111', size: 'M', stock: 9, reserved_stock: 0 },
      { id: 'v-8-l', product_id: 'p-8', sku: 'PLZ-BLK-L', colour: 'OBSIDIAN BLACK', colour_hex: '#111111', size: 'L', stock: 3, reserved_stock: 0 },
    ],
  },

  // =================== KIDS (JUNIOR ATELIER) ===================
  {
    id: 'p-9',
    name: 'JUNIOR HEAVYWEIGHT BOX TEE',
    slug: 'junior-heavyweight-box-tee',
    description:
      'Architectural minimal tee scaled for kids. Crafted from 280 GSM pure combed organic cotton with soft rib collar, drop shoulders, and non-restrictive silhouette.',
    category_id: 'cat-1',
    category: SEED_CATEGORIES[0],
    collections: [SEED_COLLECTIONS[0]],
    mrp: 249900, // ₹2,499 INR
    sale_price: 249900,
    material: '100% GOTS Organic Combed Cotton (280 GSM)',
    fit: 'Kids Relaxed Box Silhouette',
    care: 'Machine wash warm 40°C. Tumble dry low.',
    weight_g: 210,
    country_of_origin: 'India',
    gender: 'kids',
    tags: ['kids', 'junior', 't-shirt', 'cotton', 'cream', 'children'],
    status: 'active',
    rating_average: 4.9,
    rating_count: 16,
    created_at: '2026-10-06T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
    images: [
      {
        id: 'img-9-1',
        product_id: 'p-9',
        colour: 'RAW CREAM',
        url: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&auto=format&fit=crop&q=80',
        alt_text: 'Junior Heavyweight Box Tee in Raw Cream studio shot',
        position: 1,
        is_primary: true,
      },
    ],
    variants: [
      { id: 'v-9-s', product_id: 'p-9', sku: 'JR-TEE-CRM-S', colour: 'RAW CREAM', colour_hex: '#F5F0E8', size: 'S', stock: 12, reserved_stock: 0 },
      { id: 'v-9-m', product_id: 'p-9', sku: 'JR-TEE-CRM-M', colour: 'RAW CREAM', colour_hex: '#F5F0E8', size: 'M', stock: 15, reserved_stock: 0 },
      { id: 'v-9-l', product_id: 'p-9', sku: 'JR-TEE-CRM-L', colour: 'RAW CREAM', colour_hex: '#F5F0E8', size: 'L', stock: 10, reserved_stock: 0 },
    ],
  },
  {
    id: 'p-10',
    name: 'JUNIOR FRENCH TERRY HOODIE',
    slug: 'junior-french-terry-hoodie',
    description:
      'Warm and durable 380 GSM loopback French Terry hoodie with seamless double hood, reinforced bar-tack pocket stitching, and wide stretch ribbed cuffs.',
    category_id: 'cat-3',
    category: SEED_CATEGORIES[2],
    collections: [SEED_COLLECTIONS[2]],
    mrp: 449900, // ₹4,499 INR
    sale_price: 449900,
    material: '100% French Terry Cotton (380 GSM)',
    fit: 'Kids Comfort Roomy Fit',
    care: 'Machine wash cold inside out.',
    weight_g: 450,
    country_of_origin: 'India',
    gender: 'kids',
    tags: ['kids', 'junior', 'hoodie', 'sweatshirt', 'black', 'children'],
    status: 'active',
    rating_average: 5.0,
    rating_count: 14,
    created_at: '2026-10-06T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
    images: [
      {
        id: 'img-10-1',
        product_id: 'p-10',
        colour: 'DEEP BLACK',
        url: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=800&auto=format&fit=crop&q=80',
        alt_text: 'Junior French Terry Hoodie front view in Deep Black',
        position: 1,
        is_primary: true,
      },
    ],
    variants: [
      { id: 'v-10-s', product_id: 'p-10', sku: 'JR-HD-BLK-S', colour: 'DEEP BLACK', colour_hex: '#111111', size: 'S', stock: 8, reserved_stock: 0 },
      { id: 'v-10-m', product_id: 'p-10', sku: 'JR-HD-BLK-M', colour: 'DEEP BLACK', colour_hex: '#111111', size: 'M', stock: 11, reserved_stock: 0 },
      { id: 'v-10-l', product_id: 'p-10', sku: 'JR-HD-BLK-L', colour: 'DEEP BLACK', colour_hex: '#111111', size: 'L', stock: 6, reserved_stock: 0 },
    ],
  },
  {
    id: 'p-11',
    name: 'JUNIOR MODULAR UTILITY CARGO',
    slug: 'junior-modular-utility-cargo',
    description:
      'Hardwearing 100% ripstop cotton trousers equipped with elasticized comfort drawstring waist, knee dart articulation, and dual velcro utility cargo pockets.',
    category_id: 'cat-5',
    category: SEED_CATEGORIES[4],
    collections: [SEED_COLLECTIONS[0]],
    mrp: 399900, // ₹3,999 INR
    sale_price: 399900,
    material: '100% Tear-Resistant Ripstop Cotton',
    fit: 'Kids Tapered Utility Fit',
    care: 'Machine wash 40°C. Do not bleach.',
    weight_g: 320,
    country_of_origin: 'India',
    gender: 'kids',
    tags: ['kids', 'junior', 'cargo', 'pants', 'bottoms', 'children'],
    status: 'active',
    rating_average: 4.8,
    rating_count: 7,
    created_at: '2026-10-06T00:00:00Z',
    updated_at: '2026-10-06T00:00:00Z',
    images: [
      {
        id: 'img-11-1',
        product_id: 'p-11',
        colour: 'GRAPHITE GREY',
        url: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=800&auto=format&fit=crop&q=80',
        alt_text: 'Junior Modular Utility Cargo pants studio look',
        position: 1,
        is_primary: true,
      },
    ],
    variants: [
      { id: 'v-11-s', product_id: 'p-11', sku: 'JR-CRG-GRY-S', colour: 'GRAPHITE GREY', colour_hex: '#333333', size: 'S', stock: 7, reserved_stock: 0 },
      { id: 'v-11-m', product_id: 'p-11', sku: 'JR-CRG-GRY-M', colour: 'GRAPHITE GREY', colour_hex: '#333333', size: 'M', stock: 10, reserved_stock: 0 },
      { id: 'v-11-l', product_id: 'p-11', sku: 'JR-CRG-GRY-L', colour: 'GRAPHITE GREY', colour_hex: '#333333', size: 'L', stock: 5, reserved_stock: 0 },
    ],
  },
];
